export const actionTypes = {
	USER_LOGIN: 'USER_LOGIN',
	USER_LOGOUT: 'USER_LOGOUT',
	USER_ERROR: 'USER_ERROR',
	USER_LOADING: 'USER_LOADING',

	HOME_LIST: 'HOME_LIST',
	HOME_LOADING: 'HOME_LOADING',
	HOME_DETAILS: 'HOME_DETAILS',
}